version: 2.1

jobs:
  package-maven:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /parent-pom
    steps:
        - checkout

        - run:
            name: clean and package
            command: mvn clean package

  deploy-maven:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /parent-pom
    steps:
        - checkout

        - run:
            name: deploy
            command: bash .circleci/bash-deploy.bash

  increment-version:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /parent-pom
    steps:
        - checkout

        - run:
            name: increment
            command: bash .circleci/bash-increment-version.bash
  
  update-dependencies:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /parent-pom
    steps:
        - checkout

        - run:
            name: update-dependencies
            command: bash .circleci/bash-update-dependencies.bash

workflows:
  version: 2
  package:
    jobs:
      - package-maven:
          filters:
            branches:
              ignore:
                - master

  release:
    jobs:
      - package-maven:
          filters:
            branches:
              only:
                - master
      - increment-version:
          requires:
            - package-maven
      - deploy-maven:
          requires:
            - increment-version
  
  update-dependencies:
    triggers:
      - schedule:
          cron: "47 13 * * *"
          filters: 
            branches:
              ignore:
                - /.*/  # Ignore all branches
    jobs:
      - update-dependencies
