version: 2.1

jobs:
  package-maven:
    docker:
      - image: maven:3.8.4-openjdk-17

    working_directory: /parent-pom

    steps:
      - checkout

      - run:
          name: clean and package
          command: mvn clean package

  deploy-maven:
    docker:
      - image: maven:3.8.4-openjdk-17

    working_directory: /parent-pom

    steps:
      - checkout

      - run:
          name: deploy
          command: |
              git config --global user.email "${USER_EMAIL}"
              git config --global user.name "${USER_NAME}"
              CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              NEXT_VERSION=$(echo "${CURRENT_VERSION}" | awk -F'.' '{print $1"."$2"."$3 + 1}')
              git checkout -b "RELEASE-${NEXT_VERSION}"
              mvn versions:set -DnewVersion="${NEXT_VERSION}"
              git commit -am "Bump version to ${NEXT_VERSION}"
              git push origin "RELEASE-${NEXT_VERSION}"
              mvn deploy --settings ./.circleci/settings.xml
              git push -d origin "RELEASE-${NEXT_VERSION}"

workflows:
  version: 2
  package:
    jobs:
      - package-maven:
          filters:
            branches:
              ignore: /.*/

  deploy:
    jobs:
      - package-maven
      - deploy-maven:
          requires:
            - package-maven
          filters:
            branches:
              only:
                - master