version: 2.1

jobs:
  package-maven:
    docker:
      - image: maven:3.8.4-openjdk-17

    working_directory: /parent-pom

    steps:
      - checkout

      - run:
          name: clean and package
          command: mvn clean package

  deploy-maven:
    docker:
      - image: maven:3.8.4-openjdk-17

    working_directory: /parent-pom

    steps:
      - checkout

      - run:
          name: deploy
          command: |
              git config --global user.email "${USER_EMAIL}"
              git config --global user.name "${USER_NAME}"
              TAG_NAME="AUTO-COMMIT"
              # Check if the tag exists locally
              if git rev-parse -q --verify "refs/tags/$TAG_NAME" > /dev/null; then
              # Delete the local tag
              git tag -d "$TAG_NAME"
              fi
              # Check if the tag exists on the remote
              if git ls-remote --tags origin "$TAG_NAME" | grep -q "$TAG_NAME"; then
              # Delete the remote tag
              git push origin --delete "$TAG_NAME"
              fi        
              CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              NEXT_VERSION=$(echo "${CURRENT_VERSION}" | awk -F'.' '{print $1"."$2"."$3 + 1}')
              mvn versions:set -DnewVersion="${NEXT_VERSION}"
              git commit -am "Bump version to ${NEXT_VERSION}"
              git tag -a "AUTO-COMMIT" -m "Bump version to ${NEXT_VERSION}"              
              git push origin master --tags
              mvn deploy --settings ./.circleci/settings.xml

workflows:
  version: 2
  package:
    jobs:
      - package-maven:
          filters:
            branches:
              ignore:
                - master

  release:
    jobs:
      - package-maven:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: 
                - "AUTO-COMMIT"
      - deploy-maven:
          requires:
            - package-maven