version: 2.1

jobs:
  package-maven:
    docker:
      - image: maven:3.8.4-openjdk-17

    working_directory: /parent-pom

    steps:
      - checkout

      - run:
          name: clean and package
          command: mvn clean package

  deploy-maven:
    docker:
      - image: maven:3.8.4-openjdk-17

    working_directory: /parent-pom

    steps:
      - checkout

      - run:
          name: deploy
          command: bash .circleci/deploy.bash

workflows:
  version: 2
  package:
    jobs:
      - package-maven:
          filters:
            branches:
              ignore:
                - master

  release:
    jobs:
      - package-maven:
          filters:
            branches:
              only:
                - master
      - deploy-maven:
          requires:
            - package-maven