package-maven:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /parent-pom
    steps:
        - checkout

        - run:
            name: clean and package
            command: mvn clean package
