update-dependencies:
    triggers:
      - schedule:
          cron: "30 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-dependencies
