release:
    jobs:
      - package-maven:
          filters:
            branches:
              only:
                - master
      - increment-version:
          requires:
            - package-maven
      - deploy-maven:
          requires:
            - increment-version
